import { useEffect, useState } from 'react';
import { api, messageFromError } from '../api';
import Panel from '../components/Panel';
import { money, shortDate, today } from '../utils/format';

const cats=['Salary','Rent','Food','Transport','Utilities','Shopping','Health','Education','Entertainment','Travel','Debt','Other'];
const empty={type:'expense',amount:'',category:'Rent',description:'',frequency:'monthly',nextRunDate:today(),active:true};
export default function Recurring(){
 const [items,setItems]=useState([]),[form,setForm]=useState(empty),[editing,setEditing]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[processed,setProcessed]=useState(0);
 async function load(){try{const {data}=await api.get('/recurring-transactions');setItems(data.recurringTransactions)}catch(err){setError(messageFromError(err))}}
 useEffect(()=>{load()},[]);
 async function apply(){try{const {data}=await api.post('/recurring-transactions/apply-due');setProcessed(data.processed||0);await load()}catch(err){setError(messageFromError(err))}}
 function reset(){setForm(empty);setEditing(null)}
 async function save(e){e.preventDefault();setBusy(true);setError('');try{if(editing)await api.put(`/recurring-transactions/${editing}`,form);else await api.post('/recurring-transactions',form);reset();await load()}catch(err){setError(messageFromError(err))}finally{setBusy(false)}}
 async function del(id){if(!confirm('Delete this recurring rule?'))return;try{await api.delete(`/recurring-transactions/${id}`);await load()}catch(err){setError(messageFromError(err))}}
 return <div className="page-stack"><div className="page-heading"><div><div className="eyebrow">AUTOMATE YOUR ROUTINE</div><h1>Recurring Transactions</h1><p>Create monthly or yearly rules; due entries are added automatically when the app is opened.</p></div><button className="btn secondary" onClick={apply}>Apply due now</button></div>{processed>0&&<div className="alert success">Applied {processed} recurring transaction{processed===1?'':'s'}.</div>}
 <div className="content-grid two-third"><Panel title={editing?'Edit recurring rule':'Add recurring transaction'} subtitle="Great for salary, rent, subscriptions and regular bills."><form className="form-grid" onSubmit={save}><label>Type<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option value="expense">Expense</option><option value="income">Income</option></select></label><label>Amount<input required type="number" min="0.01" step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})} /></label><label>Category<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{cats.map(x=><option key={x}>{x}</option>)}</select></label><label>Frequency<select value={form.frequency} onChange={e=>setForm({...form,frequency:e.target.value})}><option value="monthly">Monthly</option><option value="yearly">Yearly</option></select></label><label>Date to start<input required type="date" value={form.nextRunDate} onChange={e=>setForm({...form,nextRunDate:e.target.value})}/></label><label>Active<select value={String(form.active)} onChange={e=>setForm({...form,active:e.target.value==='true'})}><option value="true">Active</option><option value="false">Paused</option></select></label><label className="span-2">Description<input maxLength="180" value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="e.g. apartment rent"/></label><div className="form-actions span-2"><button className="btn primary" disabled={busy}>{busy?'Saving…':editing?'Save rule':'Add rule'}</button>{editing&&<button type="button" className="btn ghost" onClick={reset}>Cancel</button>}</div></form>{error&&<div className="alert error">{error}</div>}</Panel>
 <Panel title="Recurring rules" subtitle={`${items.length} rules`}><div className="recurring-list">{items.map(r=><div className={`recurring-card ${r.active?'':'paused'}`} key={r.id}><div className="rec-icon">↻</div><div className="rec-main"><div className="row-between"><strong>{r.category} · {r.frequency}</strong><span className={`type-pill ${r.type}`}>{r.type}</span></div><div className="muted">{r.description||'Recurring transaction'} · next {shortDate(r.nextRunDate)}</div><strong className={`rec-amount amount-${r.type}`}>{r.type==='income'?'+':'−'}{money(r.amount)}</strong></div><div className="card-actions"><button className="icon-btn" onClick={()=>{setEditing(r.id);setForm({type:r.type,amount:String(r.amount),category:r.category,description:r.description||'',frequency:r.frequency,nextRunDate:r.nextRunDate,active:r.active})}}>Edit</button><button className="icon-btn danger" onClick={()=>del(r.id)}>Delete</button></div></div>)}{!items.length&&<div className="empty-state">No recurring transactions yet.</div>}</div></Panel></div>
 </div>
}
