import { useMemo, useState } from 'react';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Cell } from 'recharts';
import { api, messageFromError } from '../api';
import Panel from '../components/Panel';
import { money, money2 } from '../utils/format';

const loanDefaults={principal:500000,annualRate:9.5,months:60};
const emiCalc=(p,r,m)=>{p=+p||0;r=+r||0;m=Math.max(1,+m||1);const mr=r/1200;const e=mr===0?p/m:p*mr*(1+mr)**m/((1+mr)**m-1);return{emi:e,total:e*m,interest:e*m-p}};
const fmtNum=v=>Number(v||0).toLocaleString('en-IN',{maximumFractionDigits:2});

export default function Tools(){
 const [tool,setTool]=useState('emi');
 const tools=[['emi','EMI Calculator','Monthly loan payment'],['education','Education Loan Planner','Study + grace + repayment'],['gold','Gold Loan Calculator','Value and eligible loan'],['compare','Loan Comparison','Compare up to 5 loans'],['debt','Debt Payoff Planner','Time and interest'],['insurance','Insurance Analysis','Premium vs coverage'],['compound','Compound Interest','Lump sum + monthly saving'],['networth','Net Worth Calculator','Assets minus liabilities']];
 return <div className="page-stack"><div className="page-heading"><div><div className="eyebrow">FINANCIAL TOOLS</div><h1>Your Financial Tools</h1><p>Interactive calculators with transparent assumptions and exact-value outputs.</p></div></div><div className="tool-tabs">{tools.map(([id,title,sub])=><button key={id} className={tool===id?'active':''} onClick={()=>setTool(id)}><strong>{title}</strong><span>{sub}</span></button>)}</div><div className="tool-pane">{tool==='emi'&&<EMI/>}{tool==='education'&&<Education/>}{tool==='gold'&&<Gold/>}{tool==='compare'&&<Compare/>}{tool==='debt'&&<Debt/>}{tool==='insurance'&&<Insurance/>}{tool==='compound'&&<Compound/>}{tool==='networth'&&<NetWorth/>}</div><div className="tool-disclaimer">These calculators use the values you enter and simplified planning assumptions. Actual lender, insurer or market terms can differ.</div></div>
}

function Field({label,children,wide=false}){return <label className={wide?'wide-field':''}>{label}{children}</label>}
function ResultGrid({items}){return <div className="result-grid">{items.map(([label,value])=><div key={label} className="result-card"><span>{label}</span><strong>{value}</strong></div>)}</div>}

function EMI(){const [v,setV]=useState(loanDefaults);const r=useMemo(()=>emiCalc(v.principal,v.annualRate,v.months),[v]);const rows=Array.from({length:Math.min(12,+v.months)},(_,i)=>({month:i+1,interest:r.interest/(+v.months||1),principal:r.principal||0}));return <Panel title="EMI Calculator" subtitle="Understand monthly payment, total payment and total interest."><div className="calculator-layout"><div className="form-grid"><Field label="Loan amount"><input type="number" min="0" value={v.principal} onChange={e=>setV({...v,principal:e.target.value})}/></Field><Field label="Annual interest rate"><input type="number" min="0" step="0.01" value={v.annualRate} onChange={e=>setV({...v,annualRate:e.target.value})}/></Field><Field label="Tenure (months)"><input type="number" min="1" max="600" value={v.months} onChange={e=>setV({...v,months:e.target.value})}/></Field></div><ResultGrid items={[["Monthly EMI",money2(r.emi)],["Total payment",money2(r.total)],["Total interest",money2(r.interest)],["Interest share",`${r.total?(r.interest/r.total*100).toFixed(1):0}%`]]}/><div className="formula-box">EMI uses the standard amortizing-loan formula. For a 0% rate, principal is split evenly across the chosen tenure.</div></div><RepaymentBar principal={+v.principal} interest={r.interest}/></Panel>}

function Education(){const [v,setV]=useState({principal:800000,annualRate:8.5,studyMonths:36,graceMonths:12,tenureMonths:96});const r=useMemo(()=>emiCalc(v.principal,v.annualRate,v.tenureMonths),[v]);return <Panel title="Education Loan Planner" subtitle="Plan repayment after your study + grace period."><div className="calculator-layout"><div className="form-grid"><Field label="Loan principal"><input type="number" min="0" value={v.principal} onChange={e=>setV({...v,principal:e.target.value})}/></Field><Field label="Annual interest rate"><input type="number" min="0" step="0.01" value={v.annualRate} onChange={e=>setV({...v,annualRate:e.target.value})}/></Field><Field label="Study period (months)"><input type="number" min="0" value={v.studyMonths} onChange={e=>setV({...v,studyMonths:e.target.value})}/></Field><Field label="Grace / moratorium (months)"><input type="number" min="0" value={v.graceMonths} onChange={e=>setV({...v,graceMonths:e.target.value})}/></Field><Field label="Repayment tenure (months)"><input type="number" min="1" value={v.tenureMonths} onChange={e=>setV({...v,tenureMonths:e.target.value})}/></Field></div><ResultGrid items={[["Estimated EMI",money2(r.emi)],["Total interest",money2(r.interest)],["Total repayment",money2(r.total)],["First EMI after",`${(+v.studyMonths||0)+(+v.graceMonths||0)} months`]]}/><div className="alert info">The planner does not assume lender-specific moratorium capitalization or subsidy rules. Use your lender's sanction terms for the final repayment schedule.</div></div></Panel>}

function Gold(){const [v,setV]=useState({grams:20,price:6800,ltv:75});const value=(+v.grams||0)*(+v.price||0),eligible=value*(+v.ltv||0)/100;return <Panel title="Gold Loan Calculator" subtitle="Estimate gold value and eligible loan amount."><div className="calculator-layout"><div className="form-grid"><Field label="Gold weight (grams)"><input type="number" min="0" step="0.01" value={v.grams} onChange={e=>setV({...v,grams:e.target.value})}/></Field><Field label="Gold price / gram"><input type="number" min="0" step="0.01" value={v.price} onChange={e=>setV({...v,price:e.target.value})}/></Field><Field label="LTV %"><input type="number" min="0" max="100" value={v.ltv} onChange={e=>setV({...v,ltv:e.target.value})}/></Field></div><ResultGrid items={[["Estimated gold value",money(value)],["Estimated eligible loan",money(eligible)],["Value margin",money(value-eligible)],["LTV",`${v.ltv}%`]]}/><div className="formula-box">Eligible amount = estimated gold value × chosen LTV.</div></div></Panel>}

function Compare(){const [loans,setLoans]=useState([{name:'Loan A',principal:500000,annualRate:9,months:60},{name:'Loan B',principal:500000,annualRate:10,months:60},{name:'Loan C',principal:500000,annualRate:8.75,months:72}]);const results=loans.map((l,i)=>({name:l.name,...emiCalc(l.principal,l.annualRate,l.months),rate:l.annualRate}));return <Panel title="Loan Comparison" subtitle="Compare payment, total interest and tenure side-by-side."><div className="compare-table">{loans.map((l,i)=><div className="compare-row" key={i}><input value={l.name} onChange={e=>{const n=[...loans];n[i]={...n[i],name:e.target.value};setLoans(n)}}/><input type="number" min="0" value={l.principal} onChange={e=>{const n=[...loans];n[i]={...n[i],principal:e.target.value};setLoans(n)}}/><input type="number" min="0" step="0.01" value={l.annualRate} onChange={e=>{const n=[...loans];n[i]={...n[i],annualRate:e.target.value};setLoans(n)}}/><input type="number" min="1" value={l.months} onChange={e=>{const n=[...loans];n[i]={...n[i],months:e.target.value};setLoans(n)}}/></div>)}</div><div className="compare-head"><span>Name</span><span>Principal</span><span>Rate</span><span>Months</span></div><div className="compare-results">{results.map(r=><div className="comparison-card" key={r.name}><div><strong>{r.name}</strong><span>{r.rate}% APR · {r.months} months</span></div><div className="compare-metrics"><span>EMI <strong>{money2(r.emi)}</strong></span><span>Interest <strong>{money2(r.interest)}</strong></span><span>Total <strong>{money2(r.total)}</strong></span></div></div>)}</div><div className="chart-wrap small-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={results}><CartesianGrid strokeDasharray="3 3" stroke="#253045"/><XAxis dataKey="name" stroke="#91a4b7"/><YAxis stroke="#91a4b7" tickFormatter={v=>`₹${Math.round(v/1000)}k`}/><Tooltip formatter={v=>money(v)} contentStyle={{background:'#121a27',border:'1px solid #263449',borderRadius:12}}/><Bar dataKey="interest" radius={[8,8,0,0]}>{results.map((_,i)=><Cell key={i} fill={['#5ee7a8','#4f8cff','#b383ff','#ffb95e','#ff6b7a'][i]}/>)}</Bar></BarChart></ResponsiveContainer></div></Panel>}

function Debt(){const [v,setV]=useState({balance:300000,annualRate:15,monthlyPayment:10000});let remaining=+v.balance||0,interest=0,month=0;const monthlyRate=(+v.annualRate||0)/1200;const payment=+v.monthlyPayment||0;while(remaining>0.01&&month<1200&&payment>remaining*monthlyRate){const mi=remaining*monthlyRate;interest+=mi;remaining=remaining+mi-payment;month++}const impossible=payment>0&&monthlyRate>0&&payment<=((+v.balance||0)*monthlyRate);return <Panel title="Debt Payoff Planner" subtitle="Estimate how long a fixed monthly payment takes to clear a balance."><div className="calculator-layout"><div className="form-grid"><Field label="Current debt"><input type="number" min="0" value={v.balance} onChange={e=>setV({...v,balance:e.target.value})}/></Field><Field label="Annual interest rate"><input type="number" min="0" step="0.01" value={v.annualRate} onChange={e=>setV({...v,annualRate:e.target.value})}/></Field><Field label="Monthly payment"><input type="number" min="0" value={v.monthlyPayment} onChange={e=>setV({...v,monthlyPayment:e.target.value})}/></Field></div>{impossible?<div className="alert error">At this payment, the balance does not cover monthly interest. Increase the monthly payment.</div>:<ResultGrid items={[["Months to payoff",month],["Approx. time",`${Math.floor(month/12)}y ${month%12}m`],["Total interest",money(interest)],["Total paid",money((+v.balance||0)+interest)]]}/>}</div></Panel>}

function Insurance(){const [v,setV]=useState({premium:24000,coverage:1000000,years:20});const total=(+v.premium||0)*(+v.years||1),ratio=(+v.coverage||0)/Math.max(total,1);return <Panel title="Insurance Analysis" subtitle="View premium burden relative to chosen coverage and period."><div className="calculator-layout"><div className="form-grid"><Field label="Annual premium"><input type="number" min="0" value={v.premium} onChange={e=>setV({...v,premium:e.target.value})}/></Field><Field label="Coverage amount"><input type="number" min="0" value={v.coverage} onChange={e=>setV({...v,coverage:e.target.value})}/></Field><Field label="Years"><input type="number" min="1" value={v.years} onChange={e=>setV({...v,years:e.target.value})}/></Field></div><ResultGrid items={[["Total premium",money(total)],["Coverage",money(v.coverage)],["Coverage / premium",ratio.toFixed(1)+'×'],["Premium as % of coverage",(+v.coverage?((total/+v.coverage)*100):0).toFixed(2)+'%']]}/><div className="formula-box">This is a comparison metric, not a recommendation about how much insurance you need.</div></div></Panel>}

function Compound(){const [v,setV]=useState({principal:100000,rate:10,years:10,monthly:5000});const months=Math.max(0,Math.round((+v.years||0)*12));let balance=+v.principal||0;const mr=(+v.rate||0)/1200;const points=[];for(let i=1;i<=months;i++){balance=balance*(1+mr)+(+v.monthly||0);if(i%12===0||i===months)points.push({year:(i/12).toFixed(1),value:balance})}const contributions=(+v.principal||0)+(+v.monthly||0)*months;return <Panel title="Compound Interest Calculator" subtitle="Explore growth from an initial amount plus recurring monthly saving."><div className="calculator-layout"><div className="form-grid"><Field label="Initial amount"><input type="number" min="0" value={v.principal} onChange={e=>setV({...v,principal:e.target.value})}/></Field><Field label="Annual return / rate"><input type="number" step="0.01" value={v.rate} onChange={e=>setV({...v,rate:e.target.value})}/></Field><Field label="Years"><input type="number" min="0" max="100" value={v.years} onChange={e=>setV({...v,years:e.target.value})}/></Field><Field label="Monthly contribution"><input type="number" min="0" value={v.monthly} onChange={e=>setV({...v,monthly:e.target.value})}/></Field></div><ResultGrid items={[["Future value",money(balance)],["Total contributions",money(contributions)],["Growth / interest",money(balance-contributions)],["Months",months]]}/></div><div className="chart-wrap small-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={points}><CartesianGrid strokeDasharray="3 3" stroke="#253045"/><XAxis dataKey="year" stroke="#91a4b7"/><YAxis stroke="#91a4b7" tickFormatter={v=>`₹${Math.round(v/1000)}k`}/><Tooltip formatter={v=>money(v)} contentStyle={{background:'#121a27',border:'1px solid #263449',borderRadius:12}}/><Bar dataKey="value" fill="#5ee7a8" radius={[8,8,0,0]}/></BarChart></ResponsiveContainer></div></Panel>}

function NetWorth(){const [assets,setAssets]=useState([{name:'Cash & bank',amount:100000},{name:'Investments',amount:150000},{name:'Vehicle',amount:80000}]);const [liabilities,setLiabilities]=useState([{name:'Education loan',amount:70000},{name:'Credit card',amount:25000}]);const sum=a=>a.reduce((t,x)=>t+(+x.amount||0),0);const a=sum(assets),l=sum(liabilities);async function save(){try{await api.post('/dashboard/net-worth-snapshot',{totalAssets:a,totalLiabilities:l})}catch(e){alert(messageFromError(e,'Could not save snapshot.'))}}function edit(setter,list,i,k,val){const n=[...list];n[i]={...n[i],[k]:val};setter(n)}return <Panel title="Net Worth Calculator" subtitle="Capture assets and liabilities, then optionally save the result to your dashboard history."><div className="networth-columns"><ItemList title="Assets" items={assets} setItems={setAssets} /><ItemList title="Liabilities" items={liabilities} setItems={setLiabilities} /></div><div className="networth-summary"><div><span>Total assets</span><strong>{money(a)}</strong></div><div><span>Total liabilities</span><strong>{money(l)}</strong></div><div className="networth-main"><span>Net worth</span><strong>{money(a-l)}</strong></div><button className="btn primary" onClick={save}>Save snapshot</button></div></Panel>}
function ItemList({title,items,setItems}){return <div className="item-list"><div className="row-between"><h3>{title}</h3><button className="icon-btn" onClick={()=>setItems([...items,{name:'',amount:0}])}>+ Add</button></div>{items.map((x,i)=><div className="item-row" key={i}><input value={x.name} placeholder="Label" onChange={e=>{const n=[...items];n[i]={...n[i],name:e.target.value};setItems(n)}}/><input type="number" min="0" value={x.amount} onChange={e=>{const n=[...items];n[i]={...n[i],amount:e.target.value};setItems(n)}}/><button className="icon-btn danger" onClick={()=>setItems(items.filter((_,idx)=>idx!==i))}>×</button></div>)}</div>}
function RepaymentBar({principal,interest}){const total=principal+interest;return <div className="repayment"><div className="row-between"><span>Principal vs interest</span><span>{money(total)}</span></div><div className="stacked-bar"><div className="principal" style={{width:`${total?principal/total*100:0}%`}}/><div className="interest" style={{width:`${total?interest/total*100:0}%`}}/></div><div className="legend-line"><span><i className="legend-dot principal"/> Principal {money(principal)}</span><span><i className="legend-dot interest"/> Interest {money(interest)}</span></div></div>}
