import { useEffect, useMemo, useState } from 'react';
import { api, messageFromError } from '../api';
import Panel from '../components/Panel';
import { money, shortDate, today } from '../utils/format';

const categories=['Salary','Freelance','Rent','Food','Transport','Utilities','Shopping','Health','Education','Entertainment','Travel','Debt','Other'];
const empty={type:'expense',amount:'',category:'Food',description:'',transactionDate:today()};

export default function Transactions(){
  const [items,setItems]=useState([]),[form,setForm]=useState(empty),[editing,setEditing]=useState(null),[search,setSearch]=useState(''),[type,setType]=useState('all'),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  async function load(){try{const {data}=await api.get('/transactions');setItems(data.transactions)}catch(err){setError(messageFromError(err))}}
  useEffect(()=>{load()},[]);
  const filtered=useMemo(()=>items.filter(x=>(type==='all'||x.type===type)&&`${x.category} ${x.description}`.toLowerCase().includes(search.toLowerCase())),[items,search,type]);
  function reset(){setForm(empty);setEditing(null)}
  async function submit(e){e.preventDefault();setBusy(true);setError('');try{if(editing)await api.put(`/transactions/${editing}`,form);else await api.post('/transactions',form);reset();await load()}catch(err){setError(messageFromError(err))}finally{setBusy(false)}}
  async function del(id){if(!confirm('Delete this transaction?'))return;try{await api.delete(`/transactions/${id}`);await load()}catch(err){setError(messageFromError(err))}}
  return <div className="page-stack"><div className="page-heading"><div><div className="eyebrow">MONEY MOVEMENT</div><h1>Transactions</h1><p>Add, edit and filter your income and expenses.</p></div></div>
    <div className="content-grid two-third"><Panel title={editing?'Edit transaction':'Add transaction'} subtitle="Keep amounts positive; choose income or expense."><form className="form-grid" onSubmit={submit}><label>Type<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option value="expense">Expense</option><option value="income">Income</option></select></label><label>Amount<input type="number" min="0.01" step="0.01" required value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})} placeholder="0"/></label><label>Category<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{categories.map(x=><option key={x}>{x}</option>)}</select></label><label>Date<input type="date" required value={form.transactionDate} onChange={e=>setForm({...form,transactionDate:e.target.value})}/></label><label className="span-2">Description<input maxLength="180" value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="e.g. monthly rent"/></label><div className="form-actions span-2"><button className="btn primary" disabled={busy}>{busy?(editing?'Saving…':'Adding…'):(editing?'Save changes':'Add transaction')}</button>{editing&&<button type="button" className="btn ghost" onClick={reset}>Cancel</button>}</div></form>{error&&<div className="alert error">{error}</div>}</Panel>
    <Panel title="Transaction history" subtitle={`${filtered.length} shown`}><div className="filters"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search category or description…"/><select value={type} onChange={e=>setType(e.target.value)}><option value="all">All types</option><option value="income">Income</option><option value="expense">Expense</option></select></div><div className="table-wrap"><table><thead><tr><th>Date</th><th>Type</th><th>Category</th><th>Description</th><th className="right">Amount</th><th></th></tr></thead><tbody>{filtered.map(t=><tr key={t.id}><td>{shortDate(t.transactionDate)}</td><td><span className={`type-pill ${t.type}`}>{t.type}</span></td><td>{t.category}</td><td>{t.description||'—'}</td><td className={`right amount-${t.type}`}>{t.type==='income'?'+':'−'}{money(t.amount)}</td><td className="action-cell"><button className="icon-btn" onClick={()=>{setEditing(t.id);setForm({type:t.type,amount:String(t.amount),category:t.category,description:t.description||'',transactionDate:t.transactionDate})}} aria-label="Edit">Edit</button><button className="icon-btn danger" onClick={()=>del(t.id)} aria-label="Delete">Delete</button></td></tr>)}</tbody></table></div>{!filtered.length&&<div className="empty-state">No transactions match your filters.</div>}</Panel></div>
  </div>
}
